### Stastical Analysis. Pandas

One of the main goals of classification machine learning models is to try to find patterns that will allow the algorithm to separate the classes of samples. Usually, they do that using different approaches. People can do that too, and as a data scientist, it is important to find manually the patterns that will allow a Machine Learning algorithm to do that. Usually, we use that Statistical tools and methods.

### The tasks

- Create a jupyter notebook with a clean code.
- Study each column together and separate it from others in relation with the ***target*** column. I highly recommend you to explore the following statistical parameters:
    - Mean.
    - Median.
    - Mode.
    - Standard Deviation.
    - Variation.
    - Range of values.

- Find what columns have the highest absolute correlation with the ***target*** column (target column is specified in the data set page), and try to explain why do you think so happens. (here you can explore literature on topic.)
- Please comment on your code.
- **Load the notebook to GitHub till the day of the next meeting.**

In [2]:
# impornt the libraries
import pandas as pd

In [3]:
# import our data set
df = pd.read_csv('wineQualityWhiteRed.csv')

In [4]:
# print our data frame
df

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [5]:
# calculate the mean of the data set - function return the mean of the values for the requested column
# select the columns that I want to calculate and calculate the mean
mean_data_frame = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", 
                      "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "pH", 
                      "sulphates", "alcohol", "quality"]].mean()
# display the data set
mean_data_frame

fixed acidity             7.215307
volatile acidity          0.339666
citric acid               0.318633
residual sugar            5.443235
chlorides                 0.056034
free sulfur dioxide      30.525319
total sulfur dioxide    115.744574
density                   0.994697
pH                        3.218501
sulphates                 0.531268
alcohol                  10.491801
quality                   5.818378
dtype: float64

In [6]:
# calculate the median - returns a Series with the median value of each column
# select the columns that I want to calculate and calculate the median
median_data_frame = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", 
                        "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "pH", 
                        "sulphates", "alcohol", "quality"]].median()

# for see all range can be used only the call of the variable
# display the result
median_data_frame

fixed acidity             7.00000
volatile acidity          0.29000
citric acid               0.31000
residual sugar            3.00000
chlorides                 0.04700
free sulfur dioxide      29.00000
total sulfur dioxide    118.00000
density                   0.99489
pH                        3.21000
sulphates                 0.51000
alcohol                  10.30000
quality                   6.00000
dtype: float64

In [7]:
# calculate mode
# mode - the value that appears most often
# call the data set and calculate the mode
mode_data_frame = df.mode()

mode_data_frame

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,6.8,0.28,0.3,2.0,0.044,29.0,111.0,0.9972,3.16,0.5,9.5,6.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9976,NaN,NaN,NaN,NaN

In [9]:
# standard deviation - calculating the standard deviation of the given set of numbers, DataFrame, column, and rows
# the standard deviation is normalized by N-1 by default
# formula: Ïƒ = âˆ‘ ( X âˆ’ Î¼ ) 2 n
standard_deviation_data_frame = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", 
                                    "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "pH", 
                                    "sulphates", "alcohol", "quality"]].std() 

standard_deviation_data_frame

fixed acidity            1.296434
volatile acidity         0.164636
citric acid              0.145318
residual sugar           4.757804
chlorides                0.035034
free sulfur dioxide     17.749400
total sulfur dioxide    56.521855
density                  0.002999
pH                       0.160787
sulphates                0.148806
alcohol                  1.192712
quality                  0.873255
dtype: float64

In [13]:
# Variation - var() method calculates the variance for each column 
# see last cell for example 

variation_data_frame = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar",
                           "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "pH", 
                           "sulphates", "alcohol", "quality"]].var()

variation_data_frame

fixed acidity              1.680740
volatile acidity           0.027105
citric acid                0.021117
residual sugar            22.636696
chlorides                  0.001227
free sulfur dioxide      315.041192
total sulfur dioxide    3194.720039
density                    0.000009
pH                         0.025853
sulphates                  0.022143
alcohol                    1.422561
quality                    0.762575
dtype: float64

In [12]:
# calculate the range of values
# select the pH of the wine, Fundamentally speaking, all wines lie on the acidic side of the pH spectrum, 
# and most range from 2.5 to about 4.5 pH (7 is neutral). There are several different types of acids found in wine, 
# which will affect how acidic a wine tastes.

normal_pH_wine_range = df["pH"].between(2.5, 4.5, inclusive = False)

normal_pH_wine_range

C:\Users\user\AppData\Local\Temp\ipykernel_91952\3226630877.py:6: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  normal_pH_wine_range = df["pH"].between(2.5, 4.5, inclusive = False)

0       True
1       True
2       True
3       True
4       True
        ...
6492    True
6493    True
6494    True
6495    True
6496    True
Name: pH, Length: 6497, dtype: bool

In [15]:
# Find what columns have the highest absolute correlation with the target column 
# (target column is specified in the data set page), and try to explain why do you think so happens. 
# (here you can explore literature on topic.)

# correlation describes the relationship between variables
# Pearson Correlation by default
df_coreleation = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", 
                     "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "pH", 
                     "sulphates", "alcohol", "quality"]].corr()

# categorical variable is the variable that was assigned to column
# and the discrete variable is the variable that can change its value based on the report of the input value
# based on the result I can say that we have perfect negative correlation
# https://www.scribbr.com/statistics/pearson-correlation-coefficient/
df_coreleation

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,1.000000,0.219008,0.324436,-0.111981,0.298195,-0.282735,-0.329054,0.458910,-0.252700,0.299568,-0.095452,-0.076743
volatile acidity,0.219008,1.000000,-0.377981,-0.196011,0.377124,-0.352557,-0.414476,0.271296,0.261454,0.225984,-0.037640,-0.265699
citric acid,0.324436,-0.377981,1.000000,0.142451,0.038998,0.133126,0.195242,0.096154,-0.329808,0.056197,-0.010493,0.085532
residual sugar,-0.111981,-0.196011,0.142451,1.000000,-0.128940,0.402871,0.495482,0.552517,-0.267320,-0.185927,-0.359415,-0.036980
chlorides,0.298195,0.377124,0.038998,-0.128940,1.000000,-0.195045,-0.279630,0.362615,0.044708,0.395593,-0.256916,-0.200666
free sulfur dioxide,-0.282735,-0.352557,0.133126,0.402871,-0.195045,1.000000,0.720934,0.025717,-0.145854,-0.188457,-0.179838,0.055463
total sulfur dioxide,-0.329054,-0.414476,0.195242,0.495482,-0.279630,0.720934,1.000000,0.032395,-0.238413,-0.275727,-0.265740,-0.041385
density,0.458910,0.271296,0.096154,0.552517,0.362615,0.025717,0.032395,1.000000,0.011686,0.259478,-0.686745,-0.305858
pH,-0.252700,0.261454,-0.329808,-0.267320,0.044708,-0.145854,-0.238413,0.011686,1.000000,0.192123,0.121248,0.019506
sulphates,0.299568,0.225984,0.056197,-0.185927,0.395593,-0.188457,-0.275727,0.259478,0.192123,1.000000,-0.003029,0.038485
alcohol,-0.095452,-0.037640,-0.010493,-0.359415,-0.256916,-0.179838,-0.265740,-0.686745,0.121248,-0.003029,1.000000,0.444319
quality,-0.076743,-0.265699,0.085532,-0.036980,-0.200666,0.055463,-0.041385,-0.305858,0.019506,0.038485,0.444319,1.000000

In [12]:
# extra calculate the variance from scratch in Python
numbers = [1,2,3,4,5,6,7,8,9]

def variance(observations):
    mean = sum(observations) / len(observations)
    squared_differences = 0
    
    for number in observations:
        difference = mean - number
        squared_difference = difference ** 2
        squared_differences += squared_difference
    
    variance = squared_differences / (len(observations) - 1)
    
    return variance

print(variance(numbers))

7.5